package com.test.pruebaback.core.util.exception;

public class ArgumentosInvalidosException extends RuntimeException{
    public ArgumentosInvalidosException(String message) {
        super(message);
    }
}
