package com.test.pruebaback.core.util.exception;

public class NoEncontradoException extends RuntimeException{
    public NoEncontradoException(String message) {
        super(message);
    }
}
